// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../routing/envelope.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AlertSummary`, `NodeState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Configure a platform-appropriate persistent storage path for the alert index.
///
/// On mobile/desktop, Flutter can call this early in startup with an
/// application-specific directory. The Rust core will then append the
/// `argus_alert_index.db` filename and use that path for sled.
Future<void> configureStorageBaseDir({required String baseDir}) =>
    RustLib.instance.api.crateCoreApiConfigureStorageBaseDir(baseDir: baseDir);

Future<void> initNode() => RustLib.instance.api.crateCoreApiInitNode();

/// Start the BLE-backed mesh node on this device (idempotent).
///
/// This wires together:
/// - BLE transport (scanner + adapter)
/// - in-memory store
/// - router
/// - node run loop
///
/// and spawns the async tasks onto the existing Tokio runtime managed by
/// flutter_rust_bridge.
Future<void> startMeshNode({required String tag}) =>
    RustLib.instance.api.crateCoreApiStartMeshNode(tag: tag);

Future<String> createAlert({required AlertInput input}) =>
    RustLib.instance.api.crateCoreApiCreateAlert(input: input);

Future<String> getKnownAlerts() =>
    RustLib.instance.api.crateCoreApiGetKnownAlerts();

Future<String> getNodeState() =>
    RustLib.instance.api.crateCoreApiGetNodeState();

Future<void> receiveBlePacket({required List<int> data}) =>
    RustLib.instance.api.crateCoreApiReceiveBlePacket(data: data);

class AlertInput {
  final String sender;
  final Priority priority;
  final String payload;

  const AlertInput({
    required this.sender,
    required this.priority,
    required this.payload,
  });

  @override
  int get hashCode => sender.hashCode ^ priority.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlertInput &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          priority == other.priority &&
          payload == other.payload;
}
